twitter-auth:
    CONSUMER_KEY: ""
    CONSUMER_SECRET: ""
    TWITTER_ACCESS_TOKEN: ""
    ACCESS_TOKEN_SECRET: ""
    BEARER_TOKEN: ""

neuralspace-auth:
    NEURALSPACE_ACCESS_TOKEN: ""

languages:
    TGT_LANG: "en"